### ISSUE TITLE
Recognise users by auth if defined

### ISSUE THREAD

**Issue by Threeseven** [SpunkyBot/spunkybot#105]
Hi Alexander,

I faced the problem of loose my admin permissions when I played from another computer.  It would be nice if Spunkybot recognise that I am the same user (looking at the authname), despite the computer I'm utilizating.

I've added a new field 'auth' in 'player' table and modified the method 'check_database' of class 'Player' in order to save it in DB.
But, I see that the xlrstats table has duplicated information as guid, player name, IP, last time seen... and the admin rights.
How do I should proceed?

Regards
Matías

**Comment by alexanderkress** [comment]
Recognition the authname is not reliable. You may loose your auth within a map cycle.
This feature will never be implemented.
The qkey is the only working thing.
You just need to copy the "qkey" file from your Urbanterror42 root folder to the other PC. This ID is ingame called GUID, the only reliable identifier which will never change.
