### ISSUE TITLE
Feature Request: Add support for recording serverside demos 

### ISSUE THREAD

**Issue by ge0rdie** [SpunkyBot/spunkybot#127]
Hi AK,

Another feature request for you :-)

**Summary**
Add support for recording demos on the server:

Rcon commands are:
/rcon startserverdemo [Player Name|Player ID|All]
/rcon stopserverdemo [Player Name|Player ID|All]

Available to all admin and mod levels

**Motivation**
When recording client side demos, there can be significant lag so that the player being spec'd is getting hits when cross hairs are not on target.   Hopefully server side demos will address this.

**Additional context**

Feature is described here:  https://www.urbanterror.info/forums/topic/28657-server-side-demo-recording/

Suggest command:
!startdemo [Player Name|Player ID|All]
!stopdemo [Player Name|Player ID|All]

thanks
--ge0rdie

**Comment by alexanderkress** [comment]
this feature would only work for special UrT build binaries, correct?
and where are the records stored? none of the admins or mods would be able to access this file...
with your provided commands the implementation should be not too difficult, correct?

**Comment by ge0rdie** [comment]
Hi,

I believe it should work fine on the standard binary, mine seems to work OK.

By default, the demos are stored on the server under
.q3a/q3ut4/serverdemos   of whatever user is running the server process.

I have set up an Apache server to allow admins to download any demos they
make, quite handy for sharing them too :-)  Unfortunately, only I can do it
because it currently requires rcon access (don't want to hand THAT out)

Another great benefit is that you can create a demo of another player while
you remain playing in the game yourself.

Implementation should be quite simple as the command just needs to be
recognized and passed through to rcon.

--ge0rdie
