### ISSUE TITLE
Player with single quote in the name causes an error on the spunkybot console 

### ISSUE THREAD

**Issue by ge0rdie** [SpunkyBot/spunkybot#128]
**Summary**
I have a person using bad language on the server, but when I went to find him in the DB, he was not there.   Tried searching by name, alias and ip address, nothing.

Error resulted in player not being inserted into the DB.

**Steps to reproduce**
1.  start with a fresh player profile
2. set player name to Applejack'Al
3.  connect to the server and watch the spunkybot console

**Expected behavior**
Console shows the following error:

[18.02.2022 06:30:15] ERROR    near "Al": syntax error
Traceback (most recent call last):
  File "spunkybot/spunky.py", line 643, in parse_line
    option[action](line)
  File "spunkybot/spunky.py", line 876, in handle_userinfo
    self.game.add_player(player)
  File "spunkybot/spunky.py", line 4149, in add_player
    player.check_database()
  File "spunkybot/spunky.py", line 3393, in check_database
    curs.execute("UPDATE `player` SET `name` = '{}',`ip_address` = '{}',`time_joined` = '{}' WHERE `guid` = '{}'".format(self.name, self.address, now, self.guid))
OperationalError: near "Al": syntax error

**Runtime Environment**
* Spunky Bot version: spunkybot-1.12.2
* Python version: 2.7.18
* Operating system: Ubuntu server
* How you installed Spunky Bot (DEB/PPA, pip, source): source

**Log file / Screenshots / Console output**
If applicable, add the devel.log file from your Spunky Bot installation folder, add screenshots or console output to help explain your problem.

This is the games.log for the event:

12:14 ClientUserinfo: 7 \ip\110.225.247.195:27960\challenge\750310731\qport\8438\protocol\68\snaps\20\name\Applejack'Al\racered\3\raceblue\3\racefree\3\rate\25000\ut_timenudge\0\cg_rgb\0 255 0\cg_physics\1\cg_ghost\1\cg_autopickup\-1\color1\4\color2\5\handicap\100\sex\male\gear\gHAOWVA\authc\0\cl_guid\D6545F0B2016362B7ED4258F4AEB24B0\weapmodes\0000011102000002000200000000
 12:14 ClientUserinfoChanged: 7 n\Applejack'Al\t\3\r\3\tl\0\f0\\f1\\f2\\a0\0\a1\255\a2\0
 12:15 ClientUserinfo: 7 \ip\110.225.247.195:27960\name\Applejack'Al\challenge\750310731\qport\8438\protocol\68\snaps\20\racered\3\raceblue\3\racefree\3\rate\25000\ut_timenudge\0\cg_rgb\0 255 0\cg_physics\1\cg_ghost\1\cg_autopickup\-1\color1\4\color2\5\handicap\100\sex\male\gear\gHAOWVA\authc\0\cl_guid\D6545F0B2016362B7ED4258F4AEB24B0\weapmodes\0000011102000002000200000000
 12:15 ClientUserinfoChanged: 7 n\Applejack'Al\t\3\r\3\tl\0\f0\\f1\\f2\\a0\0\a1\255\a2\0
 12:30 ClientUserinfo: 7 \ip\110.225.247.195:27960\name\Applejack'Al\challenge\750310731\qport\8438\protocol\68\snaps\20\racered\3\raceblue\3\racefree\3\rate\25000\ut_timenudge\0\cg_rgb\0 255 0\cg_physics\1\cg_ghost\1\cg_autopickup\-1\color1\4\color2\5\handicap\100\sex\male\gear\gHAOWVA\authc\0\cl_guid\D6545F0B2016362B7ED4258F4AEB24B0\weapmodes\0000011102000002000200000000
 12:30 ClientUserinfoChanged: 7 n\Applejack'Al\t\2\r\3\tl\0\f0\\f1\\f2\\a0\0\a1\255\a2\0
 12:59 say: 7 Applejack'Al: fuck islam and fuck all muslims
 13:20 say: 7 Applejack'Al: mohammed was a paedo

**Additional context**

thanks
--ge0rdie

**Comment by alexanderkress** [comment]
hmm looks like the preparation for the mysql support create the issue with single quote. need to think about it if it is possible to fix that or if the name needs to be shorten...

**Comment by alexanderkress** [comment]
I have a fix for this issue in rel. 1.13.1.
I need some further tests to check all positions where the name value is used.

**Comment by ge0rdie** [comment]
Thanks mate, much appreciated

--ge0rdie
