### ISSUE TITLE
Prism?

### ISSUE THREAD

**Issue by that0n3guy** [SpunkyBot/spunkybot#38]
Hey, 

I just set this up on my work server :).   (using docker: https://github.com/that0n3guy/docker-spunkybot)

Can we get access to Prism?

**Comment by alexanderkress** [comment]
Hello,

PRISM is not yet released. The last beta test user failed to get it running alone. I did several redesign, but it is not ready for a release tag 1.0.
I hope that I have some free time on x-mas vacation to continue and release a pre-release soon.

I also should start with docker, sounds interesting...

**Comment by wacs** [comment]
Hello @alexanderkress I would like to tesit Prism. Is there a way to download it?

**Comment by alexanderkress** [comment]
Hello @wacs, I am currently develop more features for Prism. Just give me a couple of more days to provide a first beta version, so that you can download the package and test it.

**Comment by wacs** [comment]
Cool @alexanderkress, thanks for respond.

**Comment by joerich** [comment]
hello @alexanderkress I too would like to access Prism! any chance?

**Comment by alexanderkress** [comment]
@wacs @that0n3guy: PRISM now available. Check 
https://github.com/SpunkyBot/PRISM
