### ISSUE TITLE
Add support for command !exit to show last user to exit the server

### ISSUE THREAD

**Issue by joerich** [SpunkyBot/spunkybot#43]
this would be useful to see who last exited the server

**Comment by alexanderkress** [comment]
You mean a list of players, who left the server during a running map?
E.g. !exit -> "Last players who left: PlyA, PlyB, PlyC"
And when a new map starts this map will be reset and filled when players leave during an active map?
In case the nobody left and you use !exit, the output shall be "No players left during this match" ??

**Comment by joerich** [comment]
that would be ok, I was mainly thinking the last person leaving the server! But the last 3 would be ok too!

**Comment by alexanderkress** [comment]
Hmm only the last leaving person is so much easier to implement... Now I was fighting already how to get a dynamic list of only the last three... If I would know from the beginning, that only one person would be enough, I could already have finished this feature :-)

Since this is your idea: only the last or the last 3? Your decision...

**Comment by joerich** [comment]
Just the last would be fine!

and Thanks!!

**Comment by alexanderkress** [comment]
Arf now when the code is almost finished :-)
Ok, only the last.
What would be the proper english:
- option A: "The last player left: XX"
- option B: "Last player left: XX"
- option C: "Player last exited: XX"
- option D: ??

And in case no player left: "No player left this match" ??

**Comment by joerich** [comment]
it doesn't really matter! I guess option b?

**Comment by alexanderkress** [comment]
ok option B will be used

**Comment by BidyBiddle** [comment]
option D: "Last disconnected player:" is the most proper you can get I guess, or simply: "Last disconnect: PlayX".

Option A and B don't feel so smooth in english.

**Comment by alexanderkress** [comment]
hmm yes you are right. but is "last disconnect:" correct regarding grammar??

"Last disconnected player: Fukushukumquat"
and UrT is already forcing a line-break :-)

**Comment by alexanderkress** [comment]
and the name of the command? still "!exit" ? or "!disconnect"
if the command is "!exit", somehow the word "exit" should be in the output message or??

Damn how did it SG with their banexit command??

**Comment by joerich** [comment]
I think maybe !exit its fairly easy to remember ;)

**Comment by alexanderkress** [comment]
command will be in release 1.9, which will be release soon. want to test support to UrT 4.3.2 first...

**Comment by joerich** [comment]
I'd love to test it!

**Comment by alexanderkress** [comment]
Feature is now in the develop branch available.
Happy testing :-)

Reconnected players are automatically removed from the "last disconnected player list".
