### ISSUE TITLE
Add support for changing to different game types

### ISSUE THREAD

**Issue by joerich** [SpunkyBot/spunkybot#46]
Add support for changing to different game types
IE:
!ctf
!tdm
!gungame
!jump
!ffa

**Comment by alexanderkress** [comment]
what would be the use case?
changing when next map starts?
but then only for super admins/head admins, or?

**Comment by alexanderkress** [comment]
any recommendations?
`!ctf   or  !mode ctf`
`!ts    or  !mode ts`

**Comment by joerich** [comment]
if an admin wants to change the current game type he would enter !ctf for capture the flag
!ffa for free for all !jump for jump maps
