### ISSUE TITLE
Parsing of usernames with dodgy characters

### ISSUE THREAD

**Issue by ge0rdie** [SpunkyBot/spunkybot#58]
I had a user named `*&*$*` connect to my server, but when I looked them up by IP address in the DB, there was no entry for them in the player table.

games.log:

    1:21 ClientConnect: 8
    1:21 ClientUserinfo: 8 \ip\82.132.233.51:12857\challenge\-494207991\qport\645\protocol\68\snaps\20\name\*&*$* \rate\17500\color1\4\color2\5\handicap\100\sex\male\authc\0\cl_guid\028B2F9ABA2934A2E1D93AC40D842035
    1:21 ClientUserinfoChanged: 8 n\*&*$*\t\3\r\2\tl\0\f0\\f1\\f2\\a0\0\a1\0\a2\0
    1:22 AccountValidated: 8 -  - 0 - "0"
    1:22 ClientUserinfo: 8 \ip\82.132.233.51:12857\name\*&*$*\challenge\-494207991\qport\645\protocol\68\snaps\20\rate\17500\color1\4\color2\5\handicap\100\sex\male\authc\0\cl_guid\028B2F9ABA2934A2E1D93AC40D842035
    1:22 ClientUserinfoChanged: 8 n\*&*$*\t\3\r\2\tl\0\f0\\f1\\f2\\a0\0\a1\0\a2\0
    1:22 ClientSpawn: 0

db query:

    sqlite> select * from player where ip_address = "82.132.233.51";
    sqlite> 

There may be a bug in how the log is parsed due to the dodgy characters this name contains, resulting in the user not being inserted into the player table.

eg: these chars could cause problems with a regex etc.

**Comment by alexanderkress** [comment]
Also on Ubuntu 16.04 it is working fine for me:

```
sqlite> select * from player where ip_address = "10.0.2.2";
2|3EA...|*&*$*|10.0.2.2|2018-08-08 10:43:04...
sqlite> .exit
vagrant@ubuntu-xenial:/opt/spunkybot$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

**Comment by ge0rdie** [comment]
Weird,  I am using:

Distributor ID: Ubuntu

Description:    Ubuntu 18.04.1 LTS

Release:        18.04

Codename:       bionic


Also:  Python 2.7.15rc1


The only other thing I can think of is for the last release, I copied my
old data.sqlite db file strait over the top of the newly installed one (not
while it was running).


I did some checking, looks like it is a local DB update issue.  When I
connect as me, it is not updating my time_joined, so I am guessing that the
missing player is just because of an insert failure.


File system permissions seem all OK, if I go into SQLite client as the
game/bot user, I can update it manually.


I switched on DEBUG and no problems showed up in the console.


SOLVED


I tried starting 1.9 again to check it still worked (it did), then I
started 1.11 again, it is now working,  WTF?


I think this confirms it was a local problem and there is no issue for you
to action.


--G

**Comment by alexanderkress** [comment]
Really strange... I will do one more test with Ubuntu Bionic.
I am also using the same database (already 5 years old) with any new version of the bot, so this should be no problem.
I could just imagine, that there was a file called data.sqlite-journal file on your server, which would mean, that the database was locked (maybe you stopped the old bot while it was trying to write into the database).

The database did not change from 1.9 to 1.11, anyway I will try to check with bionic if an update from 1.9 to 1.11 leads to some similar issue.

**Comment by alexanderkress** [comment]
I did a retest with Ubuntu 18.04, used a fresh database and the user with name `*&*$* ` was found, he could register and so on.
Afterwards I tested my old database and check the update of my already existing user. The time_joined was always updated properly. So I am also not able to reproduce this issue.
