### ISSUE TITLE
How to install in Archlinux

### ISSUE THREAD

**Issue by Ygarr** [SpunkyBot/spunkybot#59]
Please add support for Archlinux. Now it is lack of some python modules

**Comment by alexanderkress** [comment]
Spunky Bot is already running on Arch Linux.
There are several server admins using ARCH, Gentoo, CentOS, OpenBSD and Ubuntu/Debian.

There is no dependency to other Python modules, you just need python2.7.

Could you please check your Python version with the command
`$ python --version`

For the installation just perform the following:
- Extract the archive: `$ tar -xzvf spunkybot-x.x.x.tar.gz`
- Move the extracted folder to the location you want to place your files to: `$ sudo mv spunkybot-x.x.x /opt/spunkybot`
- Set the ownership of this folder to the same user and group running your Urban Terror server: `$ sudo chown -R q3ut4:q3ut4 /opt/spunkybot`

**Comment by travmon** [comment]
`python2  spunky.py`
