### ISSUE TITLE
Error on bot console:  rcon_say() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by ge0rdie** [SpunkyBot/spunkybot#60]
Hi AK, not sure if this has been reported yet.

It occurs when instant_kill_spawnkiller is turned on and someone triggers it:

[05.11.2018 06:29:12] ERROR    rcon_say() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "spunkybot-1.11.0/spunky.py", line 678, in parse_line
    option[action](line)
  File "spunkybot-1.11.0/spunky.py", line 1090, in handle_kill
    self.game.rcon_say("^7%s got killed for Spawn Killing", killer_id)
TypeError: rcon_say() takes exactly 2 arguments (3 given)

Also, I often see in the chat log people asking why they were smitten, may be related, ie: killed for spawn killing message not working properly.

--G

**Comment by alexanderkress** [comment]
Hello ge0rdie,
this issue has been fixed with commit 03d6e8c, static code analyse tool found that ugly bug.

If you enabled the option "kill spawnkiller", people get killed (=smitten) in case of spawn killing.
Only the chat message is not shown, why they got killed.
