### ISSUE TITLE
Ban players matching other identifiers.

### ISSUE THREAD

**Issue by seanbarr1988** [SpunkyBot/spunkybot#62]
Currently it seems that bans are only made by IP?

But players can have multiple identifiers that might not all change at once. For example:

IP
Auth user account name
GUID

Is it possible to have  bans in place for all 3 identifiers?  It makes it slightly harder and more work for cheaters to have to get new ip > get new GUID > get new auth account.

**Comment by alexanderkress** [comment]
Hello,

bans are always done by GUID and IP.
If a player wants to join, first the GUID will be checked and if the GUID is unknown, the IP address will be checked as well.

Name or auth is not used, since these values can be changed very easy.

**Comment by seanbarr1988** [comment]
Alex in order of ease to change its easiest to change GUID, then IP.  Auth requires re-registering with a new email and activating the account. it requires then getting a new auth key and installing it. and if used properly by server owners the notoriety can prevent freshly made accounts connecting to the server. Auth is the best way to ban a player (especially if your server strictly requires auth).  I  hope someone could add this. This is one of the main reasons i found b3bot to be better than all the other bots out there,

**Comment by alexanderkress** [comment]
Just log out, and then the auth check is useless, Most players play without auth and also most servers do not require auth.
Additionally the auth system was never working reliable. Very often the authname was not shown.
It is a feature added by FS and is not part of the quake engine.
As far as I remember, FS disabled most of the auth features (tag protection etc).

Auth ban is somehow added by FS which is also not reliable and would break compatibility to other versions.
