### ISSUE TITLE
Handling of bots

### ISSUE THREAD

**Issue by seanbarr1988** [SpunkyBot/spunkybot#64]
Spunkybot doesnt seem to handle AI bot players (players with address "bot")

This creates a couple of issues.

Database is populated with bot players and their stats. - not needed / waste of space

Bots are included in team shuffles or team balancing (they should be ignored as they are placed in a specific team by the admin) i.e we dont want a game where its 4bots vs 4humans

players that teamkill bots (for valid reason i.e. to get the flag) are kicked from the server as bots will never "!FP"

there are probably other problems not yet found - essentially spunkybot should ignore bots and not count them as players. 

the easiest way to identify them by rcon is their IP address will be "BOT"

**Comment by alexanderkress** [comment]
> Database is populated with bot players and their stats. - not needed / waste of space

no stats are stored until player registers, only the join date is stored, so yes some kB could be saved :-)

> Bots are included in team shuffles or team balancing

in case the admin ensures that the same amount if bots are always in a fixed team, this may work.  so this could be a feature request

> players that teamkill bots are kicked from the server

of course, it is the same behavior as the built-in friendlyFire feature. TK is TK. and there is still the automatic forgive timer, so in case you kill a bot just one or two times in a few minutes, nothing will happen.
how do you ensure that some idiots do not teamkill all bots all the time? from my point of view it makes no sense to allow TK of bots by default. there should be an option to enable if you allow TK of bots.

**Comment by seanbarr1988** [comment]
Also on my specific issue with bots (they change their names everytime they are added to the game) this means i have about 100+ users in the database that are current bots lol.

Yes I can see your point on TK and Shuffling. Its probably best to make it an option in the config how spunkybot should handle in game bots.

**Comment by alexanderkress** [comment]
OMG :-) why are you adding 100 bots?... do you know that spunkybot has an addbot command?

The database exclusion can be done easily, so this will be added.

The shuffle command uses the rcon feature shuffleteams, so this cannot be controlled and I will not try to implement my own shuffle feature.

Allowing TK of bots can be implemented, the option to enable/disable this feature should also be simple to implement.

**Comment by seanbarr1988** [comment]
im not adding 100 bots im adding 2v2.  however each time they are kicked and re-added they come back with a new name and thus a new player number with spunkybot lol

Thanks for the other implementations :)
