### ISSUE TITLE
request: move to geoip2 

### ISSUE THREAD

**Issue by seanbarr1988** [SpunkyBot/spunkybot#66]
Just wondering if this is possible?

https://github.com/maxmind/GeoIP2-python

it would seem maxmind changed over to a new database format GeoIP.mmdb and is incompatible with pygeoip.

It would be nice to be able to use their new free GeoIP2Lite database as i have started noticing people from germany being tag as connecting from russia.

**Comment by alexanderkress** [comment]
Will not be done, as Maxmind requires an account to download the database files.
I dont believe that the file can be shared in this case.
And since the format is completely different, a total new implementation would be required.

So feel free to implement that by your own :-)

**Comment by alexanderkress** [comment]
I think a found another solution for an update of the existing database.

The package geoip-database is part of Linux, and the coming Ubuntu 20.04 has a database from Jan.2020 included. Since the license for this file is an ODbL, sharing will be allowed.

**Comment by seanbarr1988** [comment]
that sounds great - in the meantime i modified my local version to use maxmind new database 

Thanks for the great work - I have just discovered Prism and loving it also :)
