### ISSUE TITLE
Feature Request: Add discord support

### ISSUE THREAD

**Issue by seanbarr1988** [SpunkyBot/spunkybot#67]
It would be nice to see support for spunkybot to also sign into a discord server and accept all the same commands from users with matching roles as the current in game roles.

**Comment by alexanderkress** [comment]
This is not possible, since discord supports only Python >=3.5, while SpunkyBot requires Python 2.7.
Additionally this would require anyway a new product, since you need to create a new bot supporting Discord and build on that all the features which Spunky Bot has.
