### ISSUE TITLE
Remove Duplicate IP's

### ISSUE THREAD

**Issue by seanbarr1988** [SpunkyBot/spunkybot#68]
Hi (apologies for yet another issue ticket):

I modified my version of spunky bot to do two things and wanted to share them:

The first I sorted out storing ip bans in the bots-banlist in a easier to read form.

!permban section:

and then in the !unban section in added a method for removing duplicates since they where never removed from the bots-banlist.txt file after !unban.

p.s. i symlink all my bots to one ban list, so needed to use os.path.realpath()

the only way i found to do this was using fileinput module and sys module 

perhaps you know a better way of doing this, either way I wanted to try and help anyway I could.

**Comment by alexanderkress** [comment]
Hi,
all issues are welcome.

The bot-banlist.txt has no function at all for SpunkyBot.
The reason for this list was at a time, when the UAA exists, so that you could share it.

From my point of view, the file and the corresponding code can be deleted. Except there is any reason to have an additional file, since SpunkyBot stores all data in the database and e.g. PRISM is reading the database and nothing else.

**Comment by seanbarr1988** [comment]
Ok I understand - its not needed from spunkybot perspective however it is still good in my view to keep around for purposes like you describe but perhaps not worth adding extra modules for.

I like it because if something goes wrong with spunkybot or rcon there is still a backup measure of ip blocking.

**Comment by alexanderkress** [comment]
Nothing can go wrong with spunkybot :-)
Well, when you are using rcon to ban/unban IPs, then it will anyway not work.

The bot-banlist file is only used for permban, so why would you anyway want to unban a perm-banned player?

I do not even see, why your code should work... looks more like an extreme risky code with potential endless loop, no unlink of file and manipulating stdout.

The original code is just appending to the end and closing the file. Your code is like suicide and kill the files... Hopefully you are not running the bot with sudo or as root...
