### ISSUE TITLE
Feature request: Move spawn kill/kick time period out of code and into config file

### ISSUE THREAD

**Issue by ge0rdie** [SpunkyBot/spunkybot#69]
Hi AK,

I am having some issues with spawn killers.

I was wondering if you could make the spawn protection time configurable by getting the value from the config file.

I think this is the bit: 

Spawn Protection time between players deaths in seconds to issue a warning
     warn_time = 3

Keep up the good work :-)

--G

**Comment by alexanderkress** [comment]
Yes correct, this is the time within a player gets a warning, when a new respawned player is killed again.
Yes of course, this can easily be implemented and added to the config file and allow the operator to define an own value.

**Comment by ge0rdie** [comment]
Hi AK,

I was thinking about this last night.

The problem I have is that if the team balance is out,  one team will be
pinned in their spawn area by the other team (in TDM).

If I increase the spawn protection too much, the opposite will happen.  A
good player could cross half the map while still being protected.

I was wondering if it would be possible to protect based on distance
travelled from spawn ?

This would solve the problem because you could say protection is over after
5 seconds or X distance whichever is first.

That way slow players could be protected and fast players would not get an
advantage.

This may be too hard/not possible, but an interesting idea :-)

--G

**Comment by alexanderkress** [comment]
no that is impossible, it is used pinned to the respawn time.

Of course, this value is an impact if an admin does not know what he did.
Per default all UrT servers using the respawn protection of 2 sec, within this time the enemy cannot even kill you.
If the spawnkill counter is set e.g. higher than 5 sec, this would be a big disadvantage for the opponent team.

Therefore I hardcoded the value to 3 sec.
From my point of view, this value makes only seen between 2-5 secs.
2 sec : no function
3 sec: best practice value
4 sec: maybe only for noob servers
5 sec: already too long, player can reach half of map

**Comment by ge0rdie** [comment]
Sweet, thanks for checking it out :-)

--G
