### ISSUE TITLE
Feature Request: Allow ban on 3 warnings

### ISSUE THREAD

**Issue by ge0rdie** [SpunkyBot/spunkybot#70]
Hi AK,

Yet another request, this one I think is a bit more solid :-)

Currently after 3 warnings a player gets automatically kicked.

I would like to be able to change the number of warnings, and the action to a tempban with optional ban length.

Maybe something like:

```
warn_expiration = 172800 (2 days) (already exists)
warn_threshold = 3
warn_threshold_action = 0 (none) 1 (kick) 2 (ban)
warn_threshold_ban_period =  86400  (1 day)
```

My end goal is: if you get 3 warnings in 2 days, you get a 1 day TB

thanks
--G

**Comment by alexanderkress** [comment]
Hello,

this feature exists already:
# warn - warn user - !warn <name> [<reason>]
depending on the reason, the player gets ban-points. If he already has ban points and gets kicked again, he/she will get a tempban.
possible reasons: tk, lang, spam, racism

However non of these kick reasons persists more than a hour to protect the players from dump admins.

What happens, if you have some dump level 20 moderators, which warn players randomly. All these players would be banned for 2 days.
And which warning shall be counted? Beeing a spec on full server would also lead to a ban.
High ping, accidently TK without forgive... All these cases would lead to bans of players.

If you want to get rid of your players, just shutdown your server :-)

**Comment by alexanderkress** [comment]
there is a good reason, why low admins can only warn, middle admins can to short tempbans, higher admins can do several days bans and only the highest admins can do permban...

**Comment by ge0rdie** [comment]
Hi,

Thanks for that, appreciate the quick response.
I saw the ban_points table there, just didn't know how it worked :-)

--G

**Comment by alexanderkress** [comment]
for your request, I would need to know which kind of warning shall lead to ban_points. which admin level is allowed to raise a warning with ban_points. which warning shall lead to which ban_duration. shall a player get banned after 3 warnings?

**Comment by ge0rdie** [comment]
Hi AK,

I actually closed the request, but if you were interested in doing it, I
would like something like this:

With these in the config file:

warning_expiration = 3600         (how long before warnings expire)
warning_kick_threshold = 3        (kick after this many warnings)
warning_kick_reasons = obj,spam,spec
warning_ban_threshold = 3         (ban after this many warnings)
warning_ban_reasons = tk,racism,sk,name,camp
warning_ban_expiration = 3600   (how long before TB expires)

So you can configure a ban list and a kick list from available reasons,
control how many warnings for each and how long the ban is.

It also allows for warnings for reasons that don't attract a ban or a kick
by just leaving them out of the list.

--ge0rdie
