### ISSUE TITLE
Feature Request: The !exit command 

### ISSUE THREAD

**Issue by joerich** [SpunkyBot/spunkybot#85]
**Summary**
Please describe what the problem is.
This is in ref: !exit
Not really a problem But is would be nice if the response wouldn't be cleared at the end of the round

**Additional context**

**Comment by alexanderkress** [comment]
what shall this command do?
When you say "in ref:", do you mean the referee mode?

**Comment by joerich** [comment]
no, what I mean is when you use !exit it shows the last player to exit the server BUT when the round is over the user is reset?it would be cool if the player didn't get resetso on the next map if you use !exit again it would still show that player
    On Monday, July 13, 2020, 11:00:41 AM EDT, Alexander Kress <notifications@github.com> wrote:  
 
 


what shall this command do?
When you say "in ref:", do you mean the referee mode?

**Comment by alexanderkress** [comment]
and what shall be the reason for that?

**Comment by alexanderkress** [comment]
the idea of !exit is that you can punish people who leave during an active map. if the next map starts, a new match starts, so there is no need to know who left previously. Maybe 5 people leave at the end of a round, the command would just show randomly the last, who did nothing wrong.
So I dont see any benefit in this feature request.

**Comment by alexanderkress** [comment]
@joerich: what is the purpose of your feature request?

**Comment by joerich** [comment]
I have some admins who change the maps when I'm not there
this would allow the HeadAdmin to see who the last person left the server
would be a chance to see which admin didn't change the map back to the standard map

**Comment by alexanderkress** [comment]
well, this would not work, since maybe the last disconnected player is a normal user.

What you want is an additional command like `!lastadmin`, which is only displaying the last disconnected admin.
This command will then not include normal users, guests or moderators.

**Comment by ge0rdie** [comment]
Could you keep a list of the most recent 10 bot commands and who did them ?

Then you could have a !history to list them

--G

**Comment by alexanderkress** [comment]
Well, a `!history` command would be possible. But to implement this correct, it will be a lot of effort. The history should only display valid and accepted commands (exclude e.g. a guest typing `!ban blabal`) and also all help and display command shall be ignored so that only a specific set of commands is listed.

The simple implementation would be: accept everything starting with "!" from an admin, independent if is admin level will support this command, and also any `!help` or `!xlrstats` will be listed.

**Comment by alexanderkress** [comment]
This would be the simple implementation:
![history_cmd](https://user-images.githubusercontent.com/3248841/88269629-aa44f380-ccd4-11ea-8b98-17db57720099.PNG)

**Comment by alexanderkress** [comment]
but it will ignore currently all aliases, e.g. `!h` will be ignored
