### ISSUE TITLE
Feature Request: Add config item to set what admin_role ius included in spawnkill feature 

### ISSUE THREAD

**Issue by ge0rdie** [SpunkyBot/spunkybot#93]
Hi AK,

**Summary**
I have some admins who are spawn killing with impunity.
Seems unfair that non-admins get smitten while admins can get away with it.
It would be great to have the admin_role threshold for the smite be  set in the config file.

**Motivation**
Here is the spot in the code:

# spawn killing - warn/kick or instant kill
 if (self.spawnkill_autokick or self.kill_spawnkiller) and self.spawnkill_warn_time and killer.get_admin_role() < 40:

Thanks
--G

**Comment by alexanderkress** [comment]
Hi ge0rdie,

this is a good idea. Shall there be one definition in the config file, which will set the minimum admin level for the spawn-kill and also the team-kill check? Shall this parameter also apply to the ping check?
Today every admin >=40 is protected (ping check, TK, spawnkill, bad words).

**Comment by ge0rdie** [comment]
I think a single param for spawn and team kill and bad words, as they are both game play related, 
Maybe a separate one for the ping test 
--G
