### ISSUE TITLE
Dedicated cyclemaps

### ISSUE THREAD

**Issue by Threeseven** [SpunkyBot/spunkybot#94]
It wil be nice to have a way to set different mapcycles for different game modes and tied to the commands that changes the mode.
For example, !ffa command sets the FFa game mode and the dedicated map (if there is any).

**Comment by alexanderkress** [comment]
It would require to ignore the mapcycle.txt file and force the different mapcycles as part of the bot settings.conf file (same as small_cycle and big_cycle feature).

If this would be sufficient, it would be somehow possible to implement, but very ugly...

**Comment by Threeseven** [comment]
My ugly hack, working in SpunkyBot 1.12.2
Sorry, I'm not a dev and I hadn't fully red the code.
